### ISSUE TITLE
Error importing JSON provided - Validation error

### ISSUE THREAD

**Issue by Secmotic** [fiwoo-platform/bulk-data#35]
Browser: Safari
User: fiwoo.platform

![captura de pantalla 2018-05-31 a las 11 44 35](https://user-images.githubusercontent.com/11160554/40775315-0984932c-64c8-11e8-9496-429c59abfe53.png)

**Comment by vladiricoemergya** [comment]
Can you attach the JSON file?

**Comment by Fiwoo** [comment]
Solved, user friendly issue in frontend
